branch-defaults:
  default:
    environment: Weather-app-2-env
    group_suffix: null
global:
  application_name: weather-app-2
  branch: null
  default_ec2_keyname: null
  default_platform: .NET 8 running on 64bit Amazon Linux 2023
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
